### PR TITLE
Add button for Animal Lost & Found to homepage

### PR DESCRIPTION
**Pull request by calebhaye**
Please don't merge this PR until a CNAME DNS Record for animals.sonomafireinfo.com is pointed to sonomafireanimals.continuousintegrations.com has been created (as per this #3)

### CODE REVIEW

**Comment by calebhaye** [comment]
FYI - here's what it looks like: 

screen shot 2017-10-11 at 2 01 32 am

**Comment by abhiyerra** [comment]
@calebhaye @danawoodman this is ready and rebased with recent changes

**Comment by calebhaye** [comment]
Looks good to me, thanks @abhiyerra 

@danawoodman this should be ready to go!

**Comment by danawoodman** [comment]
Online!

**Pull request merged**
